#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xrdb -merge ~/.Xresources
/usr/bin/pipewire &
/usr/bin/pipewire-pulse &
/usr/bin/pipewire-media-session &
udiskie --tray &
xsetroot -cursor_name left_ptr
picom &
lxpolkit &
feh --bg-scale ~/wallpaper.png
~/.config/polybar/launch.sh &
redshift &
mailsync &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          30

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp state=floating follow=on
bspc rule -a mpv state=floating
bspc rule -a Screenkey manage=off
bspc rule -a Firefox state=tiled
bspc rule -a Firefox:Browser state=floating
bspc rule -a Firefox:Dialog state=floating
bspc rule -a Firefox:firefox state=floating
bspc rule -a Firefox:Prompt state=floating
notify-send "If you're not asked for your password, sync your mails manually with mailsync to unlock pass!"
